version: '3.3'

services:
  influxdb:
    image: influxdb:2.2
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=streaming
      - DOCKER_INFLUXDB_INIT_BUCKET=top-level
    container_name: influxdb